#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/common.sh

function resource_check() {
  jq -rn \
    --arg version "" \
    '{
      "version": $version
    }'
}

if [[ ${BASH_SOURCE[0]} != $0 ]]; then
  export -f resource_check
else
  set -euo pipefail

  resource_check "${@:-}"
  exit $?
fi
